name: Basic pipeline 
env:
  PYTHON_VERSION: "3.10"

on: push 

jobs:
  basic-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: xetdata/checkout@v1
      - name: Create data
        run: |
          ./etl.sh 
      - name: Peek Data output
        run: |
          head -n 10 data/data.csv
